const settings = require('./settings.cjs');

async function jsonRequest(url, options = {}) {
  const response = await fetch(url, {
    ...options,
    redirect: 'error',
    signal: AbortSignal.timeout(10000),
  }).catch((error) => {
    throw new Error(
      `Cannot reach ${url}: ${error.cause?.code || error.message}`,
    );
  });
  if (!response.ok)
    throw new Error(`${new URL(url).pathname}: HTTP ${response.status}`);
  return response.json();
}

async function graphql(query, variables = {}, token) {
  const body = await jsonRequest(settings.graphqlURL, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      ...(token
        ? { authorization: `Bearer ${token}` }
        : { 'x-hasura-admin-secret': settings.adminSecret() }),
    },
    body: JSON.stringify({ query, variables }),
  });
  if (body.errors)
    throw new Error(`GraphQL: ${body.errors.map((e) => e.message).join('; ')}`);
  return body.data;
}

async function course() {
  const data = await graphql(
    'query($code: String!) { course(where: {code: {_eq: $code}}) { id code name } }',
    { code: settings.courseCode },
  );
  if (data.course.length !== 1)
    throw new Error(
      `Course ${settings.courseCode} missing. Import course data or set E2E_COURSE_CODE.`,
    );
  return data.course[0];
}

async function register(account) {
  return jsonRequest(`${settings.apiURL}/auth/email/register`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      first_name: account.firstName,
      last_name: account.lastName,
      email: account.email,
      password: account.password,
    }),
  });
}

async function removeAccount(account) {
  if (!/^uwflow-e2e-[0-9a-f-]{36}@example\.invalid$/.test(account.email)) {
    throw new Error(
      'Refusing cleanup of an account not generated by the E2E fixture.',
    );
  }
  // The only cleanup target is the unique account generated for this test.
  // Recover a token even if signup succeeded but a later UI assertion failed.
  const response = await fetch(`${settings.apiURL}/auth/email/login`, {
    method: 'POST',
    redirect: 'error',
    signal: AbortSignal.timeout(10000),
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ email: account.email, password: account.password }),
  });
  const body = await response.json();
  if (response.status === 401 && body.error === 'email_not_registered') return;
  if (!response.ok || !body.token)
    throw new Error(
      `Cleanup login failed for ${account.email}: HTTP ${response.status}`,
    );
  const result = await fetch(`${settings.apiURL}/user`, {
    method: 'DELETE',
    redirect: 'error',
    signal: AbortSignal.timeout(10000),
    headers: { authorization: `Bearer ${body.token}` },
  });
  if (!result.ok)
    throw new Error(
      `Cleanup failed for ${account.email}: HTTP ${result.status}`,
    );
  const remaining = await graphql(
    'query($id: Int!) { user(where: {id: {_eq: $id}}) { id } review(where: {user_id: {_eq: $id}}) { id } user_course_taken(where: {user_id: {_eq: $id}}) { user_id } }',
    { id: body.user_id },
  );
  if (
    remaining.user.length ||
    remaining.review.length ||
    remaining.user_course_taken.length
  )
    throw new Error(`Cleanup left rows for ${account.email}`);
}

async function markCourseTaken(userId, courseId) {
  await graphql(
    'mutation($user: Int!, $course: Int!) { insert_user_course_taken_one(object: {user_id: $user, course_id: $course, term_id: 1261}) { user_id } }',
    { user: userId, course: courseId },
  );
}

async function reviews(userId, courseId, token) {
  const data = await graphql(
    'query($user: Int!, $course: Int!) { review(where: {user_id: {_eq: $user}, course_id: {_eq: $course}}) { id course_comment course_easy course_useful liked public } }',
    { user: userId, course: courseId },
    token,
  );
  return data.review;
}

module.exports = {
  graphql,
  course,
  register,
  removeAccount,
  markCourseTaken,
  reviews,
};
